- hosts: terraform-ansible
  tasks:
  # Instalando os pacotes necessários na Instância AWS
  - name: Instalando docker
    shell: "sudo apt update -y && sudo apt install -y docker.io && sudo apt install -y docker-compose"
  - name: outros pacotes
    shell: "sudo apt install -y zip; sudo apt install tar"
  - name: copiado wordpress atualizado
    shell: "wget https://br.wordpress.org/latest-pt_BR.tar.gz"
  - name: decompactando
    shell: "tar xzf latest-pt_BR.tar.gz"
  - name: chmos
    shell: "sudo chmod 777 wp-content/"
  - name: enviando arquivos
    copy:
        src: 'reverse_proxy/nginx.conf'
        dest: '~/reverse_proxy/nginx.conf'
        owner: ubuntu
        group: ubuntu
        mode: 0644
  - name: enviando arquivos 2
    copy:
        src: 'reverse_proxy/proxy.conf'
        dest: '~/reverse_proxy/proxy.conf'
        owner: ubuntu
        group: ubuntu
        mode: 0644
  - name: enviando arquivos 3
    copy:
        src: 'apache2/ports.conf'
        dest: '~/apache2/ports.conf'
        owner: ubuntu
        group: ubuntu
        mode: 0644
  - name: enviando dockerfile
    copy:
        src: 'dockerfile'
        dest: '~/dockerfile'
        owner: ubuntu
        group: ubuntu
        mode: 0644
  - name: enviando dockerfile
    copy:
        src: 'docker-compose.yml'
        dest: '~/docker-compose.yml'
        owner: ubuntu
        group: ubuntu
        mode: 0644
  - name: dockerfile
    shell: "sudo docker build -t php8 ."
  - name: docker-compose"
    shell: "sudo docker-compose up -d"
  - name: restart apache2
    shell: sudo docker exec  ubuntu_wordpress_1 service apache2 start