- hosts: terraform-ansible
  tasks:
  # Instalando os pacotes necessários na Instância AWS
  - name: Instalando docker
    shell: "sudo apt update -y && sudo apt install -y docker.io && sudo apt install -y docker-compose"
  - name: outros pacotes
    shell: "sudo apt install -y zip; sudo apt install tar"
  - name: copiado wordpress atualizado
    shell: "wget https://br.wordpress.org/latest-pt_BR.tar.gz"
  - name: decompactando
    shell: "tar xzf latest-pt_BR.tar.gz"


  - name: copyando 
    ansible.builtin.copy:
      src: apache2/ports.conf
      dest: /apache2/
      owner: ubuntu
      mode: '0755'

  - name: copyando nginx.conf
    ansible.builtin.copy:
      src: /reverse_proxy/nginx.conf
      dest: /reverse_proxy/nginx.conf
      owner: ubuntu
      group: ubuntu
      mode: '0755'

  - name: copyando proxy.conf
    ansible.builtin.copy:
      src: /reverse_proxy/proxy.conf
      dest: /reverse_proxy/proxy.conf
      owner: ubuntu
      group: ubuntu
      mode: '0755'

  - name: copyando Dockerfile
    ansible.builtin.copy:
      src: /dockerfile
      dest: /
      owner: ubuntu
      group: ubuntu
      mode: '0755'
    
  - name: copyando  
    ansible.builtin.copy:
      src: docker-compose.yml
      dest: /docker-compose.yml
      owner: ubuntu
      group: ubuntu
      mode: '0755'

  - name: rodando o docker-file
    shell: "sudo docker build -t php8 . "
  - name: rodando o docker-compose"
    shell: "sudo docker-compose up -d"
    