- hosts: terraform-ansible
  tasks:
  # Instalando os pacotes necessários na Instância AWS
  - name: Instalando docker
    shell: "sudo apt update -y && sudo apt install -y docker.io && sudo apt install -y docker-compose"
  - name: outros pacotes
    shell: "sudo apt install -y zip; sudo apt install tar"
  - name: copiado worpress atualizado
    shell: "wget https://br.wordpress.org/latest-pt_BR.tar.gz"
  - name: decompactando
    shell: "tar xzf latest-pt_BR.tar.gz"
    